<?php

return [
    'user_model' => App\Models\User::class,
    'resources' => [
        'enabled'                   => true,
        'class'                     => Rmsramos\Activitylog\Resources\Activitylogs\ActivitylogResource::class,
        'label'                     => 'Activity Log',
        'plural_label'              => 'Activity Logs',
        'resource_action_label'     => 'View Activity Log',
        'hide_resource_action'      => false,
        'hide_restore_action'       => false,
        'hide_restore_model_action' => true,
        'navigation_item'           => true,
        'navigation_group'          => 'Administration',
        'navigation_icon'           => 'heroicon-o-clipboard-document-list',
        'navigation_sort'           => 100,
        'navigation_count_badge'    => false,
        'default_sort_column'       => 'created_at',
        'default_sort_direction'    => 'desc',
        'allow_delete'              => false,
        'allow_bulk_delete'         => false,
    ],
    'pagination' => [
        'per_page_options' => [10, 25, 50, 100],
        'default_per_page' => 10,
    ],
    'timeline' => [
        'enabled' => true,
        'icons'   => [
            'created'    => 'heroicon-o-plus-circle',
            'updated'    => 'heroicon-o-pencil-square',
            'deleted'    => 'heroicon-o-trash',
            'restored'   => 'heroicon-o-arrow-path',
            'attached'   => 'heroicon-o-link',
            'detached'   => 'heroicon-o-link-slash',
            'replicated' => 'heroicon-o-document-duplicate',
            'default'    => 'heroicon-o-information-circle',
        ],
        'colors' => [
            'created'    => 'success',
            'updated'    => 'info',
            'deleted'    => 'danger',
            'restored'   => 'warning',
            'attached'   => 'success',
            'detached'   => 'danger',
            'replicated' => 'info',
            'default'    => 'gray',
        ],
        'labels'          => [],
        'show_properties' => true,
        'show_causer'     => true,
        'show_subject'    => true,
        'show_timestamp'  => true,
        'action_label'    => 'Activity Timeline',
        'action_icon'     => 'heroicon-o-clock',
        'limit'           => 10,
        'with_relations'  => [],
    ],
    'restore' => [
        'enabled'                  => true,
        'hide_restore_action'      => false,
        'restore_action_label'     => 'Restore',
        'require_confirmation'     => true,
        'show_in_relation_manager' => true,
        'show_in_resource'         => true,
        'allowed_events'           => ['updated', 'deleted'],
        'excluded_fields'          => [
            'id',
            'created_at',
            'updated_at',
            'deleted_at',
            'password',
            'remember_token',
            'email_verified_at',
        ],
    ],
    'relation_manager' => [
        'enabled'              => true,
        'show_badge'           => true,
        'show_timeline_action' => true,
        'show_batch_action'    => true,
        'show_restore_action'  => true,
        'show_view_action'     => true,
        'allow_bulk_delete'    => false,
    ],
    'auto_log' => [
        'enabled' => true,
        'actions' => [
            'create'       => true,
            'edit'         => true,
            'delete'       => true,
            'restore'      => true,
            'attach'       => true,
            'detach'       => true,
            'replicate'    => true,
            'force_delete' => true,
        ],
        'editable_columns' => true,
        'bulk_actions'     => true,
    ],
    'filters' => [
        'date_range'   => true,
        'causer'       => true,
        'subject_type' => true,
        'subject_id'   => true,
        'event'        => true,
        'log_name'     => true,
    ],
    'date_format'     => 'd/m/Y',
    'datetime_format' => 'd/m/Y H:i:s',
    'relative_time'   => true,
    'performance' => [
        'eager_load_causer'  => true,
        'eager_load_subject' => true,
        'cache_enabled'      => false,
        'cache_ttl'          => 3600,
    ],
    'loggers' => [
        'enabled'       => true,
        'directory'     => app_path('Filament/Activitylog/Loggers'),
        'namespace'     => 'App\\Filament\\Activitylog\\Loggers',
        'auto_discover' => true,
        'registered'    => [
            // \App\Filament\Activitylog\Loggers\UserLogger::class,
        ],
    ],
    'pruning' => [
        'enabled'               => true,
        'older_than_days'       => 365,
        'keep_important_events' => true,
        'important_events'      => ['created', 'deleted', 'restored'],
    ],
    'notifications' => [
        'enabled'  => false,
        'channels' => [
            'database' => true,
            'mail'     => false,
            'slack'    => false,
        ],
        'events' => [
            'deleted'  => true,
            'restored' => true,
        ],
        'critical_events' => [
            'deleted',
            'payment.failed',
        ],
        'roles'        => [],
        'notify_users' => [],
        'thresholds'   => [],
        'digest'       => [
            'enabled'        => true,
            'frequency'      => 'daily',
            'time'           => '09:00',
            'min_activities' => 5,
        ],
        'quiet_hours' => [
            'enabled' => false,
            'start'   => '22:00',
            'end'     => '08:00',
        ],
    ],
    'export' => [
        'enabled'        => env('ACTIVITY_LOG_EXPORT_ENABLED', true),
        'download_route' => null,
        'limits' => [
            'max_records' => 10000,

        ],
        'excel' => [
            'include_summary' => true,

        ],
    ],
];
